Repository illuin-tech/vidore-benchmark, pull requests merged in 2025-02, with the labels that each got.

#79 Package restructure
  .github/workflows/test.yml
  .python-version
  CHANGELOG.md
  README.md
  pyproject.toml
  skypilot/l4/config.yaml
  src/vidore_benchmark/cli/convert_ds_to_beir.py
  src/vidore_benchmark/cli/examples/convert_vidore_benchmark_to_beir.sh
  src/vidore_benchmark/cli/main.py
  src/vidore_benchmark/evaluation/__init__.py
  src/vidore_benchmark/evaluation/evaluate.py
  src/vidore_benchmark/evaluation/interfaces.py
  src/vidore_benchmark/evaluation/scoring.py
  src/vidore_benchmark/evaluation/vidore_evaluators/__init__.py
  src/vidore_benchmark/evaluation/vidore_evaluators/base_vidore_evaluator.py
  src/vidore_benchmark/evaluation/vidore_evaluators/vidore_evaluator_qa.py
  src/vidore_benchmark/main.py
  src/vidore_benchmark/retrievers/README.md
  src/vidore_benchmark/retrievers/__init__.py
  src/vidore_benchmark/retrievers/base_vision_retriever.py
  src/vidore_benchmark/retrievers/bge_m3_colbert_retriever.py
  src/vidore_benchmark/retrievers/bge_m3_retriever.py
  src/vidore_benchmark/retrievers/biqwen2_retriever.py
  src/vidore_benchmark/retrievers/bm25_retriever.py
  src/vidore_benchmark/retrievers/cohere_api_retriever.py
  src/vidore_benchmark/retrievers/colidefics3_retriever.py
  src/vidore_benchmark/retrievers/colpali_retriever.py
  src/vidore_benchmark/retrievers/colqwen2_retriever.py
  src/vidore_benchmark/retrievers/dse_qwen2_retriever.py
  src/vidore_benchmark/retrievers/dummy_vision_retriever.py
  src/vidore_benchmark/retrievers/jina_clip_retriever.py
  src/vidore_benchmark/retrievers/nomic_retriever.py
  src/vidore_benchmark/retrievers/registry_utils.py
  src/vidore_benchmark/retrievers/siglip_retriever.py
  src/vidore_benchmark/retrievers/vision_retriever.py
  src/vidore_benchmark/utils/__init__.py
  src/vidore_benchmark/utils/data_utils.py
  src/vidore_benchmark/utils/image_utils.py
  tests/cli/test_e2e_evaluate_retriever.py
  tests/cli/test_evaluate_retriever.py
  tests/data/e2e_vidore_results/bm25_tabfquad.json
  tests/data/e2e_vidore_results/colsmol_256M_tabfquad.json
  tests/evaluation/test_evaluate.py
  tests/evaluation/vidore_evaluators/conftest.py
  tests/evaluation/vidore_evaluators/test_vidore_evaluator_qa.py
  tests/retrievers/test_dummy_vision_retriever.py
  tests/retrievers/test_jina_clip_retriever.py
  tests/utils/test_data_utils.py
Labels: enhancement

#84 Add `--num-workers` option in CLI
  CHANGELOG.md
  README.md
  src/vidore_benchmark/cli/main.py
  src/vidore_benchmark/retrievers/base_vision_retriever.py
  src/vidore_benchmark/retrievers/bge_m3_colbert_retriever.py
  src/vidore_benchmark/retrievers/bge_m3_retriever.py
  src/vidore_benchmark/retrievers/biqwen2_retriever.py
  src/vidore_benchmark/retrievers/bm25_retriever.py
  src/vidore_benchmark/retrievers/cohere_api_retriever.py
  src/vidore_benchmark/retrievers/colidefics3_retriever.py
  src/vidore_benchmark/retrievers/colpali_retriever.py
  src/vidore_benchmark/retrievers/colqwen2_retriever.py
  src/vidore_benchmark/retrievers/dse_qwen2_retriever.py
  src/vidore_benchmark/retrievers/dummy_vision_retriever.py
  src/vidore_benchmark/retrievers/jina_clip_retriever.py
  src/vidore_benchmark/retrievers/nomic_retriever.py
  src/vidore_benchmark/retrievers/registry_utils.py
  src/vidore_benchmark/retrievers/siglip_retriever.py
Labels: enhancement

#87 Add support for BEIR datasets
  CHANGELOG.md
  README.md
  src/vidore_benchmark/cli/main.py
  src/vidore_benchmark/evaluation/vidore_evaluators/base_vidore_evaluator.py
  src/vidore_benchmark/evaluation/vidore_evaluators/vidore_evaluator_beir.py
  src/vidore_benchmark/evaluation/vidore_evaluators/vidore_evaluator_qa.py
  tests/cli/test_e2e_evaluate_retriever.py
  tests/cli/test_evaluate_retriever.py
Labels: enhancement

#88 Set qrels scoring to integer type
  src/vidore_benchmark/cli/convert_ds_to_beir.py
  src/vidore_benchmark/evaluation/vidore_evaluators/vidore_evaluator_beir.py
Labels: bug

#89 Fix qrels score type in BEIR conversion script
  src/vidore_benchmark/cli/convert_ds_from_qa_to_beir.py
Labels: bug

#90 Clarify usage modes in README
  README.md
Labels: documentation

#91 Fix eval mode in vision_retriever
  src/vidore_benchmark/retrievers/vision_retriever.py
Labels: bug

#94 Prepare v5.0.0 package restructure release
  CHANGELOG.md
  src/vidore_benchmark/cli/convert_ds_from_qa_to_beir.py
Labels: documentation

#95 Make python API quickstart snippet clearer
  README.md
Labels: documentation

#97 Clarify BEIR expected type for IDs
  src/vidore_benchmark/evaluation/vidore_evaluators/vidore_evaluator_beir.py
Labels: documentation, enhancement
